// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOjnVfqBWJX-b9fmIdBTW3H9iwDPJdgA',
    appId: '1:394565682284:web:a0f095ac0ae3a6d7e9c449',
    messagingSenderId: '394565682284',
    projectId: 'chatting-app-86c7e',
    authDomain: 'chatting-app-86c7e.firebaseapp.com',
    storageBucket: 'chatting-app-86c7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlyJZ5Kl9lgpRITuQnAVxWPgR0v-FfP4',
    appId: '1:394565682284:android:4b8fc1f3e9bf46bfe9c449',
    messagingSenderId: '394565682284',
    projectId: 'chatting-app-86c7e',
    storageBucket: 'chatting-app-86c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFyPq3G4W3NFReA21zt6XW7kvqDM9YTH4',
    appId: '1:394565682284:ios:cd220ed13c433177e9c449',
    messagingSenderId: '394565682284',
    projectId: 'chatting-app-86c7e',
    storageBucket: 'chatting-app-86c7e.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFyPq3G4W3NFReA21zt6XW7kvqDM9YTH4',
    appId: '1:394565682284:ios:cd220ed13c433177e9c449',
    messagingSenderId: '394565682284',
    projectId: 'chatting-app-86c7e',
    storageBucket: 'chatting-app-86c7e.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOjnVfqBWJX-b9fmIdBTW3H9iwDPJdgA',
    appId: '1:394565682284:web:b5b613079557914ae9c449',
    messagingSenderId: '394565682284',
    projectId: 'chatting-app-86c7e',
    authDomain: 'chatting-app-86c7e.firebaseapp.com',
    storageBucket: 'chatting-app-86c7e.firebasestorage.app',
  );
}
